### ISSUE TITLE
Missing branch labels in figure 8

### ISSUE THREAD

**Issue by ralienpp** [VDA5050/VDA5050#10]
Not all the branches of the flowchart in fig. 8 are labeled, so one is forced to spend extra time to figure out which is which:

![image](https://user-images.githubusercontent.com/295338/114676332-7d74b880-9d09-11eb-9160-a3ff020830d7.png)

**Comment by KIT-IFL** [comment]
Fixed in 6463f619b46c640a70282461146cc0b31b5af423
