### ISSUE TITLE
[Question] agvProtocolFeatures - is the `resultDescription` on the correct level?

### ISSUE THREAD

**Issue by ljaniec** [VDA5050/VDA5050#106]
Unclear definition:
* actionParameters [actionParameter] in agvProtocolFeatures - is resultDescription on the correct level? Shouldn't it be inside {...} above for actionParameter element? The second closing curly bracket seems to be from agvActions above.

Can you add an example full datasheet for a robot to return after requesting it?

**Comment by MaximilianPenninger** [comment]
resultDescription is on the same level like actionParameters, actionScopes and so on. It's a free text for a verbose result-description.

**Comment by ljaniec** [comment]
Ok, got it
