### ISSUE TITLE
Outdated timestamp and headerId for last will

### ISSUE THREAD

**Issue by ralienpp** [VDA5050/VDA5050#11]
The connection status message is supposed to be retained and transmitted as a last will. When the will is delivered in case of a connection outage, its  `timestamp` and `headerId` will be outdated.

Perhaps the specification could explicitly say that developers should watch out for this aspect, emphasizing that this would be the timestamp and headerId from the time the message was originally sent by the AGV, so the fact that they're "in the past" is expected.

**Comment by MaximilianRies** [comment]
Yeah I remember thinking about this aspect but not writing this down. We should fix that.

**Comment by KIT-IFL** [comment]
Fixed in https://github.com/VDA5050/VDA5050/commit/eb756de8e4728e2433a569cbd76a3d26103d9dd2
