### ISSUE TITLE
Are nodes with different theta but same xy have same nodeId? And how to just do rotation at node?

### ISSUE THREAD

**Issue by MeetYyj** [VDA5050/VDA5050#113]
Should Node {"x“: 2.0, "y": 1.0, "theta":0 }  and Node {"x“: 2.0, "y": 1.0, "theta":PI/2 } have same nodeId?
And if so, how to do rotation at node?
For example, AGV is now at { "nodeId":"1", "nodePosition":{"x“: 2.0, "y": 1.0, "theta":0 } }, I want AGV just rotate itself at node 1 from theta 0 to PI/2. Should I just send an order with one Node { "nodeId":"1", "nodePosition":{"x“: 2.0, "y": 1.0, "theta":PI/2 } }, and an emty edge?  (Notice that order's first node is not in deviation theta range of AGV's current position)
Thanks.

**Comment by AntonDueck** [comment]
the edge is not empty it is from Node0 to Node0 and with the nodseq on the first Node0 is diffrent to the second Node0 nodeseq

**Comment by MeetYyj** [comment]
thanks

**Comment by wb2110** [comment]
how to skip the first Node0 for efficiency?
