### ISSUE TITLE
No definition of AGV reference point in factSheet

### ISSUE THREAD

**Issue by ljzhu01** [VDA5050/VDA5050#114]
There is no definition of AGV reference point in factSheet. The reference point is the pivot point that is stationary when AGV/AMR rotates, and can be used as the reference point for the reported position by the AGV/AMR.

In physicalParameters, there are only width and length.

In agvGeometry, there is envelope2d and envelope3d.

Is the reference point info missing, or is it assumed to be just (0,0) in the AGV's reference frame?

**Comment by AntonDueck** [comment]
yes it is so assuemed

**Comment by ConstantinUp** [comment]
VDA/VDMA: It is assumed so. We will clarify that in future Versions.

**Comment by KIT-IFL** [comment]
This was clarified with PR #277 for Version 2.1.0 with an additional comment on the reference point.
