### ISSUE TITLE
[change request] need battery status of re-calibration

### ISSUE THREAD

**Issue by luanrp** [VDA5050/VDA5050#115]
the batterCharge reported by AGV will get inaccurate  after few days usage,  the AGV need to perform a full charge to correct it; meanwhile, regular full charge will extend the battery’s life.

suggest to add a boolean value "needRecalibrate" into batteryState,  if true, MC will schedule a full charge on appropriate times. 

AGV can report the needRecalibrate true at any time, not only on low battery level or charging.

**Comment by AntonDueck** [comment]
you could use  warning msgs to communicate the battery issue.  Because i think this ist the payload witch will be logged, and not the whole status.
