### ISSUE TITLE
Undefined structure `infoReference`

### ISSUE THREAD

**Issue by ralienpp** [VDA5050/VDA5050#12]
The `info` data structure references an `infoReference` data structure (page 36), however it is not defined anywhere.

**Comment by MaximilianRies** [comment]
You are right. This needs to be fixed. The structure was thought to be just like `errorReference`, but we missed to include it.

**Comment by stephanlante** [comment]
Discussion within VDA and VDMA started

**Comment by KIT-IFL** [comment]
#34 fixes this issue.
