### ISSUE TITLE
master or develop

### ISSUE THREAD

**Issue by AntonDueck** [VDA5050/VDA5050#120]
why is the master newer then the develop

the version 2.0 is Release but not in the git. 
[VDA 5050 2.0](https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Flink.mediaoutreach.meltwater.com%2Fls%2Fclick%3Fupn%3DDHOeDFB06ArU-2FMuHV2UEAmfIhdLL3Ideep8A8gYNfk-2BhB-2FsfTndKYozNnukamAGXq7PqGr59gZuub9x2rYttpQClKg-2FkutY73DyQt1VB9Mvoc7oPjh8IeeLidrcVSr9pukhAUgHNExV4MMCVz69KCq5D5RAgg5ouYk0mRSyCG9d8jpYX7QAtcj5Dqshqx-2FLkvxBnJTQRHGLy0nvmFW-2BTQEXGqGH0-2F898MS-2BEwkxDyg0YhmmY1wjKkNBd4TcSpUL4mbdtOgcnrCPVaKq96OCq783QPpXN5vDruBWmMsICKfv9quia5-2B5NQjh-2FmkLej5S0RDDnFR1qRKg2njr0yX60YCdG41zOXAKYESDBPnpnzVgrq9Gtpsl55TwSZe0zzVrbCkb-2FHnUS9wON5KzxPKLQAkGf51SHTAGgRm4PglTFTzoeWzoV4dRUA5loLV7JHum3AnFId3SQs-2FAQXNcQbRI1b-2BeBflbg3jhmRfS0g-2Bix3orDsBN2taNXqlk6CEN-2FMpfX-2BcglWV8HFabBIk6xFzEAzixAV11ZxYKzEzEnCbvjjg0yLcadwhfRCIwJV9jukdvroDb4PYCZJ8zSeqt-2FXNuaU6RK-2Bi082mWLLXtDwFofteqyH2DyX3x-2FQ1ipjq0AwSgB7mEyZQosxhiI2YUHvsgNDA-3D-3DoWgY_i4CCCbn5-2F8KYUiSF19pRD3WS53cEtTXToOeKU8zGhyBlRSdOfxoSSKnuYzdwehlhXaZm60e2NEMRNtvzd1MwTu2lqO803m31EHInnlGC180INegqXYHzeCJ4mc3XcSMsuRL3RhbvnyxU2JWfFOXLJBxj00YmqZIMlyGPpQTBKWLCvjeH4ILLtnCgKp8vGryCfLFrg9fa30zpKhGFabCj-2F4HhdueCH9p7B8PL3Jq5TYE8jluJ0xF73uhVumT7IxYStLZAKMOB6zh-2BsRyH1JBflje9CkffeRmz5htG0N5VWgTRSVXN2d7AXOMpK27FWVnyY4e-2Bqn6fS20zlopxllluWXRQJkc3kf7o3zSd6iLvupNXw72fjPx0EZ6HKwoJSReJcVj1PHVxrHyeleBuyZsdqg-3D-3D&data=04%7C01%7Clena.anzenhofer%40vda.de%7C9441906ed5a44ee3ccc708da027460b8%7C511cd8f2368040ba999273f9acafa8d8%7C0%7C0%7C637824996106431683%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=ug%2B9OwZfMdGOYoD%2FXh51ueotut%2BBWdXUrGAcjft2nkc%3D&reserved=0)

**Comment by ConstantinUp** [comment]
In main, the currently published version of the VDA 5050 should always be available.
The development branch was updated and is now ahead of the main branch
