### ISSUE TITLE
Consistent notation of ranges

### ISSUE THREAD

**Issue by eka-bohlmann** [VDA5050/VDA5050#142]
Hello,

in chapter 6 the notation for specifying ranges is not consistent.
After some feedback from colleagues we like to suggest to introduce a consistent notation for ranges in the VDA 5050 specification:
- Inclusive ranges with square brackets 
- Three point ellipsis
- Infinity is not a number, this should be specified as max.value or min.value (instead of negative infinity)
- explicit floating-point values if data type is float
Examples:
- [0.0 ... 1.0]
- [1 ... int64.max]

Best 
Karsten

**Comment by ConstantinUp** [comment]
Accepted by VDA/VDMA Team
