### ISSUE TITLE
Problem with 'localizationParameters' in Factsheet

### ISSUE THREAD

**Issue by f-uba** [VDA5050/VDA5050#147]
In the factsheet topic we have a parameter named 'localizationParameters', which is of type JSON-object, with the description: "Detailed specification of localization".

However, when we look for this parameter in the json schema of the facsheet we only get this:

```
"localizationParameters": {
        "type": "integer",
        "description": "Detailed specification of localization"
    }
```

And in the documentation the term 'localizationParameters' has no further references. Also in the documentation, the type shown in the schema above is wrong, because it is named as an integer, not as JSON-object.

If 'localizationParameters' is correct, how can I use a detailed specification with an integer type? Is there a table to compare the variable values and get a reference from that?

**Comment by KIT-IFL** [comment]
This was, in fact a typo, resulting from previous versions. Since an implementation without the necessary information was not possible, the parameter is removed for the release candidate of version 2.1.0 with PR #277
