### ISSUE TITLE
Improve usability of order diagrams through a different notation

### ISSUE THREAD

**Issue by ralienpp** [VDA5050/VDA5050#16]
Currently, VDA5050 uses numbers for both, node names and node sequence numbers:

![image](https://user-images.githubusercontent.com/295338/114679441-713e2a80-9d0c-11eb-9180-42b61cad14ee.png)

This leads to an ambiguity, when one says “the AGV goes from 6 to 8”, does it mean “node6 to node8” or “seq6 through seq8”? In the example following example I used letters to name nodes, so if I say “from B to D” it is unambiguous, and so is “from 2 to 6”:
![image](https://user-images.githubusercontent.com/295338/114679639-a3e82300-9d0c-11eb-8d27-f00ac00548b8.png)

This will make it a bit easier to cooperate with other people, say, when you're debugging something together and you need to make references to certain parts of the map.

**Comment by MaximilianRies** [comment]
As for the node names in the documentation: You are right, we could use some other names. The way it looks now, it may seem that the node names are supposed to be numbers - that is not the case, it was just more conevenient to draw.

In fact, node names can be any valid, unique string - UUIDs are suggested, although verbalizing them and talking about them probably is not that convenient.

The sequence number is only a check for conitunity in the order. It can be refered to if you want to reason about an order with loops, but it will probably change on the next order.

**Comment by KIT-IFL** [comment]
Discussed in core team and implemented with PR #252
