### ISSUE TITLE
Clarify the allocation logic for sequence numbers

### ISSUE THREAD

**Issue by ralienpp** [VDA5050/VDA5050#17]
The specification says this about sequence numbers: _"This sequenceId runs over the nodes and edges (first node of an order receives a 0, the first edge then gets the 1, the second node then gets the 2, and so on). This allows for easier tracking
of the order progress."_

This leaves room for interpretation, for example - are gaps in the sequence allowed? i.e., would this be OK `10 20 30 34`? This becomes a sensitive issue in cases such as https://github.com/VDA5050/VDA5050/issues/15, where an order update diverges from the previously defined horizon, forcing either a reuse of previously assigned sequence numbers, or the introduction of such gaps.

**Comment by MaximilianRies** [comment]
You are right, this needs to be clarified. The intent is that there's always an increment of 1 from node to edge to node and so on.

**Comment by KIT-IFL** [comment]
https://github.com/VDA5050/VDA5050/blame/main/VDA5050_EN_V1.md#L545

here is the line where the handlingn of the `sequenceId` is clarified.
