### ISSUE TITLE
Missing CHANGELOG

### ISSUE THREAD

**Issue by FPurchess** [VDA5050/VDA5050#171]
A changelog / version history is missing.

As far as we're aware there's no way to understand protocol changes between v1.x / v2.x apart from manually comparing / diffing the PDFs, which is a quite tedious work. Please let us know how / where to retrieve a change history of the protocol.

**Comment by AntonDueck** [comment]
the problem it the not existing history of the mark down document.
see explanation #152

**Comment by FPurchess** [comment]
Hi @AntonDueck, thanks for your response. However, this issue is not related to the file format or git history. When maintainers release new major versions of the protocol, the community wants to know what changed and how the versions are (backward)-compatible.

Currently all engineers have to manually "diff" the PDFs and then identify the changes between the payloads/topics and the potential compatibility-issues. That's not only tedious, but will also make it very hard for the protocol to find adoption across engineers.

**Comment by KIT-IFL** [comment]
@FPurchess We have added the deprecated version 1.1 as a new branch. You can compare the changes from version 1.1 to version 2.0 here: https://github.com/VDA5050/VDA5050/compare/1.1.0...2.0.0
Please Note: As already described by @AntonDueck, the project was only created as an open source project after the release of version 1.1. So the branch 1.1 was only a working version at any time. Officially the versions published by the VDA are always valid. Nevertheless, the above diff makes it easier to understand the main changes (adding the factsheet and adjusting variable names).

We hope it helps you anyway!
