### ISSUE TITLE
[Clarification required] Erasure of FINISHED action states during an order

### ISSUE THREAD

**Issue by leierseder-jh** [VDA5050/VDA5050#185]
According to the description field of field `state.actionStates`, this array
> Contains a list of the current actions and the actions, which are yet to be finished. This may include actions from previous nodes, that are still in progress.

But - in the same field:
> The action state is kept until a new order is received.

Following the common definition of "an order" as everything which is scoped by one `orderId`, these statements are somehow contradictory, as the first sentence suggests to not keep states of finished actions across multiple updates (but only such "which are yet to be finished"), the second sentence states the opposite.

**Possible interpretation:**

State of actions with state FINISHED are reported just once, then removed from the `state.actionStates` array.
State of actions with state != FINISHED are repeatedly reported until a new order was received (according to Flowchart "accepting orders"/Figure 8).

**Comment by collani-bosch** [comment]
I would (and we do) list all action states inside state message, until a new orderId is used. The state of instant actions are also inside the state and if you keep into account that a message can be lost (QoS Level 0) you may lose a state if some state will be automatically deleted.

**Comment by KIT-IFL** [comment]
We provided a clarification of the use of state.actionState within the proposed changes of version 2.1.0 in PR #277.
