### ISSUE TITLE
Node vs NodeState member order discrepancy

### ISSUE THREAD

**Issue by JWCS** [VDA5050/VDA5050#186]
This is a minor discrepancy, related to serialization.
The `node` message order:
nodeId, sequenceId, nodeDescription, **released, nodePosition**, actions
The `nodeState` message order:
nodeId, sequenceId, nodeDescription, **nodePosition, released**
I don't know how breaking message order is to the spec, but presumptuously I would think the nodeState released member should go before the position, like in the node message.

**Comment by collani-bosch** [comment]
The data format is JSON and the order of the fields doens't matter.
"An object is an unordered set of name/value pairs." (e.g. see [JSON](https://www.json.org/json-en.html))

**Comment by JWCS** [comment]
I know, so the level of this is of a minor nitpick, but with regards to consistency, this should be so. But, if it's too minor, it can just be closed; I thought I'd at least mention it as an implementer's observation.
