### ISSUE TITLE
ErrorReference and InfoReference: two object names for the same object structure

### ISSUE THREAD

**Issue by JWCS** [VDA5050/VDA5050#191]
Under section 6.10.6 (State topic: Implementation), for the `errors [error]` state json element, there's an `errorReferences [errorReference]` element. Additionally, for the state `information [info]` element, there's an `infoReferences [infoReference]` element. 
Both ErrorReference and InfoReference have the exact same json object structure and definition (just quoting one):
<html>
<body>

errorReference { |   | JSON-object |  
-- | -- | -- | --
referenceKey |   | string | References the type of reference (e.g., headerId, orderId, actionId, etc.).
referenceValue} |   | string | References the value, which belongs to the reference key.

<br class="Apple-interchange-newline">
</body>
</html>

First, since these message definitions are redundant, wouldn't it simplify to just call the object `reference`, leading to `errorReferences [reference]`, `infoReferences [reference]`? Although since each is already under an error or info object, the prefix identifier is still a bit redundant.

Secondly, and perhaps this is still better, the structure of a Reference and an ActionParameter (the first definition, for an Action, found in 7.2) are effectively the same, except key/value became referenceKey/referenceValue. Is there a plain name for this? Does the structure need a different name in each invocation, when there's already a context and an element name?
Ex. Parameter, List, Qualifier, Dict?

**Comment by KIT-IFL** [comment]
In our view, this change request is a programming optimization. In your opinion, are there any advantages that would justify a breaking change? If so, please feel free to reopen the issue. Thank you for your contribution!
