### ISSUE TITLE
Changed writing from   "allowedDeviationXy" (schema) to "allowedDeviationXY" (as written in specification)

### ISSUE THREAD

**Issue by joachimfeld** [VDA5050/VDA5050#195]
As in the specification always   "allowedDeviationXY" in 1.1 and 2.0 was used the team decided to change it also in the schema. 

Decision was taken 9.3.23 in the VDA5050 team

**Comment by KIT-IFL** [comment]
We decided to use the variable name "allowedDeviationXY" as it is specified in the PDF version. This was fixed in pull request #208.
