### ISSUE TITLE
Ambiguity: implied position deviation range zone between two nodes with allowedDeviationXY nonzero

### ISSUE THREAD

**Issue by JWCS** [VDA5050/VDA5050#197]
This seems simple and intuitive, and implied but its not actually stated, that the zone between the two order.nodePositions with nonzero allowedDeviationXY circles is itself a set of valid poses for the vehicle while traversing the order.edge.

There is no edge parameter otherwise specifying rotational or positional limits (except not to rotate), so this seems to be the desired implementation. 
<p align="center">
<img src="https://user-images.githubusercontent.com/10385237/225756115-f8f6c1e7-b771-4320-8bbf-60ed1620cba1.png"/>
</p>

However, there's another ambiguity: when provided an edge.trajectory (which may go wildly outside of the straight-line between the two edge nodes). For this case, there is no deviation parameter specified, and the implied edge deviation seems inapplicable.

Suggested resolution:
1. Explicitly mention in the spec that it is implied and desired that the AMR can navigate through the space between the two nodes' allowedDeviationXY circles.
2. (Discussion required) Add a parameter to edge: the allowed deviation from the straight-line between nodes.
    i. This could then be an overriding constraint on the zone introduced by the nodePosition.allowedDeviationXY
    ii. It would allow more traversal tolerance when desired nodePosition.allowedDeviationXY is near-zero.
    iii. For edge.trajectory, this applies cleanly; unless someone wants a dynamically sized margin to each knot...

**Comment by collani-bosch** [comment]
The current version of the norm is focused on AGVs, which are moving (more or less) on the edge from one node to another. How to deal with AMRs is highly in discussion. See also: #73 or #175

**Comment by KIT-IFL** [comment]
We are currently working on the corridor implementation which allow a similar use of AMRs in the VDA 5050 context. Please see #175. Feel free to contribute to this discussion.
