### ISSUE TITLE
Field "theta" in nodePosition optional/required

### ISSUE THREAD

**Issue by burgefeSICKAG** [VDA5050/VDA5050#199]
The field _nodePosition_ (optional itself) contains the optional field _theta_.

What's confusing is that while field _theta_ is optional according to the order schema (_node/nodePosition_), it is required according to the state schema (_nodeState/nodePosition_). 

According to the VDA doc there is only one _nodePosition_ JSON object, thus _theta_ should be either optional or required everywhere.

Is there a reason why the field is required for vehicle state feedback?

**Comment by collani-bosch** [comment]
I think this is an error inside the schema files and should be fixed there. The text of version 1.1 is mistakable, but since version 2.0 it's clear that the document text is binding.
