### ISSUE TITLE
Flowcharts usability improvements

### ISSUE THREAD

**Issue by ralienpp** [VDA5050/VDA5050#21]
- [ ] Consolidate duplicate branches
- [ ] Vertical orientation

Flowcharts could be simplified by refactoring, because some of the branches are nearly identical, here is an example:
![image](https://user-images.githubusercontent.com/295338/114685548-45be3e80-9d12-11eb-9b69-044938b4c0d5.png)

The second point is about the fact that I have to either turn my head around or rotate the document multiple times whenever I'm dealing with some of the more complex figures of the specification.

If the flowchart is simplified and does not contain redundant elements, it can fit nicely into a vertical layout. I'm attaching [my "from scratch" drawing of the same flowchart](https://github.com/VDA5050/VDA5050/files/6309813/vda5050-order-flowcharts.zip), you can open it in software like yED (free), which can also “prettify” the flowchart using various automatic layout algorithms.

**Comment by KIT-IFL** [comment]
Accepted in 2021-08, added in 416e935. Thank you very much for your improvements.
