### ISSUE TITLE
Create community page for VDA5050-related resources

### ISSUE THREAD

**Issue by ralienpp** [VDA5050/VDA5050#22]
It would be great if there were a community wiki or something like it, where resources relevant to this standard could be shared. For example, so far during my work with the specification I've got several things that might come in handy to others:
- a [stricter JSON schema](https://github.com/VDA5050/vd-m-a-5050/pull/11)
- a [VDA 5050 payload visualizer](http://vda5050.arculus.de/), for easier debugging and replicating scenarios

**Comment by KIT-IFL** [comment]
We will add a wiki with community ressources and link your projects there. Thank you for your input!
