### ISSUE TITLE
[Feature Request] ErrorHint field in the Error object.

### ISSUE THREAD

**Issue by jammoul271** [VDA5050/VDA5050#223]
In the current version of VDA, the error message has the following structure : 

| error { |                  | JSON-Object | Description                                                                                              |
| ------- | ---------------- | ----------- | -------------------------------------------------------------------------------------------------------- |
|         | errorType        | String      | Type/name of error                                                                                       |
|         | *errorReferences*  | Array       | Array of references to identify the<br>source of the error (e.g., headerId,<br>orderId, actionId, etc.). |
|         | *errorDescription* | String      | Error description.                                                                                       |
|         | errorLevel       | String      | Enum {WARNING, FATAL}                                                                                    |
| }       |                  |             |

For operators, error messages alone are sometimes not enough to understand the situation or know the appropriate measure to take to resolve issues.
Therefore, we suggest adding a new optional field called errorHint, to allow error messages to contain a possible solution. This would help operators know how to act in certain scenarios when problems occur.

The new Error object would be : 

| error { |                  | JSON-Object | Description                                                                                              |
| ------- | ---------------- | ----------- | -------------------------------------------------------------------------------------------------------- |
|         | errorType        | String      | Type/name of error                                                                                       |
|         | *errorReferences*  | Array       | Array of references to identify the<br>source of the error (e.g., headerId,<br>orderId, actionId, etc.). |
|         | *errorDescription* | String      | Error description.                                                                                       |
|         | errorLevel       | String      | Enum {WARNING, FATAL}                                                                                    |
|         | *errorHint*        | String      | Possible solution for the error                                                                          |
| }       |                  |             |

**Comment by KIT-IFL** [comment]
Input from the core team meeting: An additional parameter would be a good help for understanding the errors, especially from the end user point of view. If we add the parameter, we would have to extend the description of the two parameters _errorReferences_ and _errorDescription_ to show, what each parameter stands for.

@jammoul271 could you create a PR for this issue and close the issue? Further discussions should take place in the pull request.
@SusanneJunghans could you add a draft for an extended description of the parameters?

**Comment by jammoul271** [comment]
Here's the link for pull request #236 

Thank you!
