### ISSUE TITLE
Miniscule Grammatical Correction

### ISSUE THREAD

**Issue by gauspohl** [VDA5050/VDA5050#226]
Missing possessive form on the final "nodes" in the below sentence:
"The first node of an order must be trivially reachable for the AGV. This means either that the AGV is already standing on the node, or that the AGV is in the **nodes** deviation range."

It should instead read:
"The first node of an order must be trivially reachable for the AGV. This means either that the AGV is already standing on the node, or that the AGV is in the **node's** deviation range."

**Comment by gauspohl** [comment]
I'll probably just submit PRs for things like this. I've reached out to Andreas Scherb for who best to speak to in order to get that going.

**Comment by KIT-IFL** [comment]
This is fixed in PR #288.
