### ISSUE TITLE
Software/Hardware/Network Information in FactSheet 

### ISSUE THREAD

**Issue by jammoul271** [VDA5050/VDA5050#228]
In the messages coming from the vehicle, there is no information related to the current software/hardware/network configuration.

Adding this information can help operators identify what software version they are running, and know if there are any changes to the hardware or network settings.  

As this kind of information is only required to be sent once or on change, we find it more appropriate in the FactSheet messages to avoid bloating the State messages.

We propose adding a new optional field called agvStatus in the following structure: 

| *agvStatus* { |                         | JSON-Object          | Description                              |
| ----------- | ----------------------- | -------------------- | ---------------------------------------- |
|             | *hardware [hardwareInfo]* | Array of JSON-Object | Hardware information.                    |
|             | *network*                 | JSON-Object          | Network information.                     |
|             | *softwareVersion*         | String               | Software version running on the vehicle. |
| }           |                         |                      |                                          |

Since not all vehicles contain the same hardware components, the "hardware" field should follow the key-value-pair structure in order to allow integrators to decide for themselves what information is relevant: 

| *hardwareInfo* { |       | JSON-Object | Description                       |
| -------------- | ----- | ----------- | --------------------------------- |
|                | key   | String      | Key of the hardware information.   |
|                | value | String      | Value of the hardware information. |
| }              |       |             |                                   |

For network information, we have opted for the following structure: 

| *network* { |            | JSON-Object      | Description                             |
| --------- | ---------- | ---------------- | --------------------------------------- |
|           | *dnsServers* | Array of Strings | List of DNS servers used by the vehicle. |
|           | *ntpServers* | Array of Strings | List of NTP servers used by the vehicle. |
|           | *ipAddress*  | String           | Local IP address of the vehicle.         |
| }         |            |                  |                                         |

We find this information useful for MC and operators to have a general overview of their devices.

Here's a possible example : 

```
"agvStatus": {
    "hardware": [
        {
            "key": "plcSoftChecksum",
            "value": "0x4297F30C"
        },
        {
            "key": "cameraSerialNumber",
            "value": "0620NL51805A0"
        },
        {
            ...
        }
    ],
    "network": {
        "dnsServers": [
            "8.8.8.8"
        ],
        "ipAddress": "192.168.0.34",
        "ntpServers": [
            "81.169.224.6"
        ],
    },
    "softwareVersion": "v1.10.1"
}
```

**Comment by KIT-IFL** [comment]
Input from the core team: 
- More precise description of the ip address needed (local or public? --> The IP of the vehicle to communicated with MC)
- Default Gateway and Net Mask might be necessary as well
- Software-Version as a key-value-pair as done with hardware

@jammoul271 could you create a PR?

**Comment by jammoul271** [comment]
PR Created #239
