### ISSUE TITLE
Missmatch translational allowedDeviation between order topic documentation and schema

### ISSUE THREAD

**Issue by burgefeSICKAG** [VDA5050/VDA5050#229]
The documentation states that a `nodePosition` may specify an optional property `allowedDeviationXY`
![image](https://github.com/VDA5050/VDA5050/assets/92976378/fd4508ea-8d78-4912-bbeb-e53068ee1961)

whereas the order schema refers to `allowedDeviationXy`
https://github.com/VDA5050/VDA5050/blob/main/json_schemas/order.schema

Since the schema permits additional properties, the schema check succeeds on receiving an order containing a node with `allowedDeviationXY`, but this value is not associated with  `allowedDeviationXy` in the subsequent operations, i.e.,  `json.contains("allowedDeviationXy")` will fail as if no deviation was provided by the order.

This may lead to Fleet Management Sytems that follow either the documentation or schema specification and thus inconsistencies within the communication.

**Comment by collani-bosch** [comment]
Yes, differences between the document and the schemas are not nice. Normally the PDF document defines the truth and with the version 2.1 it is additional mentioned inside the document: "If there are differences between the JSON schemas and this document, the variant in this document applies."
