### ISSUE TITLE
Clarification: can an order update remove a horizon?

### ISSUE THREAD

**Issue by ralienpp** [VDA5050/VDA5050#23]
Suppose you send an order like this:
![image](https://user-images.githubusercontent.com/295338/114864619-817c0580-9df1-11eb-8dc8-e8358ae38aa8.png)
- the base only covers the first 3 nodes, up to node `90`
- the rest is the horizon

Then you send an order update, to extend the base further up to `107`:
![image](https://user-images.githubusercontent.com/295338/114864762-a96b6900-9df1-11eb-9d59-3d84e6dde707.png)
- note that although the base is extended, the horizon has been removed

This looks like a special case of horizon modification https://github.com/VDA5050/VDA5050/issues/15, where the horizon is simply removed altogether. 

The specification does not say this explicitly, so it is better to double-check - is the horizon set in stone, and can it be **only extended**? Or are such modifications as depicted here, or in issue #15, also valid?

**Comment by MaximilianPenninger** [comment]
I think this is defined clearly. In the German version it says

> Die Leitsteuerung hat die Möglichkeit, die Fahrbefehle der Fahrroute „Horizon“ zu ändern. 

In the English draft it says

> MC has the option to make changes to the horizon by sending entirely different nodes as the new base. 

For me, both say clearly, that the horizon can change. From my point of view, the word "change" of course includes "delete".

**Comment by collani-bosch** [comment]
I agree, "change" includes "delete". The alternative would be to change the nodes inside the horizon to identical nodes with edges of length zero. I think this is covered by the norm, but is more a corner case than a typically formed order.

**Comment by MaximilianPenninger** [comment]
> The alternative would be to change the nodes inside the horizon to identical nodes with edges of length zero.

No, in my opinion this is no option. Think of track-guided AGVs, that are using RFID-Tags for Localization. They are typically not prepared for "non-movement-edges".

**Comment by collani-bosch** [comment]
@MaximilianPenninger: Yes, I think this leads to a lot of problems, but we haven't found anything in the norm which says "Don't do it." Do you know the section, which says this is forbidden?

**Comment by ralienpp** [comment]
Thanks for the clarification. I believe it would be a bit more reassuring if the text were edited to explicitly say that deleting a horizon is acceptable, e.g. : "MC has the option to make changes to the horizon by sending entirely different nodes, _or deleting some of them_."

**Comment by stephanlante** [comment]
In discussion within VDA and VDMA

**Comment by KIT-IFL** [comment]
Added the clarification to the specification in https://github.com/VDA5050/VDA5050/commit/e19cc603884eb45a15cb3c90700955ec8ed66b5e.
