### ISSUE TITLE
System architecture for integrating VDA5050 with the OpenRMF

### ISSUE THREAD

**Issue by Ashwini-Rathi** [VDA5050/VDA5050#230]
Hello,

My project focuses on implementing the VDA5050 protocol on AGVs in the physical world. However, before going forward with this implementation on physical AGVs, I am planning to demonstrate it in the virtual world in order to debug the issues before implementing it on PLC-based AGVs. So, I am planning to integrate VDA5050 with [OpenRMF](https://github.com/open-rmf)
It would help with a system architecture or set of instructions on how to integrate these both in either [Openrmf demos](https://github.com/open-rmf/rmf_demos) or user-defined tasks.
Thanks in advance.

**Comment by AntonDueck** [comment]
you may look at [ros vda 5050 ](https://github.com/NVIDIA-ISAAC/isaac_mission_dispatch)

**Comment by Ashwini-Rathi** [comment]
@AntonDueck thank you for the post. 
It did help me. However, the [robot client section](https://github.com/nvidia-isaac/isaac_mission_dispatch#robot-setup) which gives mission updates and robot status updates with VDA5050 feedback messages do not have the complete schema. 
I am looking to implement the schema mentioned in VDA5050 manual with the help of [VDA5050 Mission Client Simulator ](https://github.com/nvidia-isaac/isaac_mission_dispatch#1-vda5050-mission-client-simulator)

Do you have any recommendations for this?

**Comment by AntonDueck** [comment]
It gets more and more off topic have to close the issue.
