### ISSUE TITLE
[feature requests]: add a filed "blockingType" into factsheet(agvProtocolFeatures. agvActions)

### ISSUE THREAD

**Issue by luanrp** [VDA5050/VDA5050#233]
Refer to factsheet's definition: agvActions: List of all actions with parameters supported by this AGV. This includes standard actions specified in VDA5050 and manufacturer-specific actions.

for manufacturer-specific actions, we can't get the information of what blockingType of a given action, I suggest to add a field into agvAction's structure.

**Comment by LukasSchwarz4202** [comment]
Whether an action should be blocking or not must be decided either by the supervisor (load handing) or by the LIF. Therefore I do not thing the vehicle has anything to say about it and I would not add it to the factsheet.

**Comment by KIT-IFL** [comment]
This suggestion was agreed on in the core team meeting and was added to the release candidate of version 2.1.0 in PR #279.
