### ISSUE TITLE
Question about the format of timestamp in header

### ISSUE THREAD

**Issue by qq625610984** [VDA5050/VDA5050#234]
The timestamp in the header is described as follows
 > Timestamp (ISO 8601, UTC); YYYY-MM-DDTHH:mm:ss.ssZ (e.g.“2017-04-15T11:40:03.12Z”)

But I noticed that the timestamp format specified in ISO8601 is as follows
> YYYY-MM-DDThh:mm:ss[.mmm]TZD

I would like to know what the `.ss` in the document means. I thought it meant milliseconds, but it only had two digits instead of three, so I was confused.
Also, I would like to ask if the end of the timestamp must be `Z`, and if timestamps like `2022-10-18T10:05:45+08:00` or `2022-10-18T10:05:45.529+08:00` are legal ?

**Comment by AntonDueck** [comment]
the `.ss` is a known type it schuld be `.ff` for fraction of a second, fix is in prepare

you provides timestamps are valid ISO8601 but there are not UTC if you have UTC then you habe a Z at the end

**Comment by ConstantinUp** [comment]
These Changes have been merged and are planned for publication in Version 2.1.0
