### ISSUE TITLE
[Change Request]: connection-topic with MQTT-QOS level 1 instead of 0

### ISSUE THREAD

**Issue by LukasSchwarz4202** [VDA5050/VDA5050#24]
We suggest to change the MQTT quality of service level of the connection-topic from 0 to 1

Arguments for the change (example):
- The AGV connects to the broker (including the configuration of the last-will) and then sends a connection-telegram ONLINE which is lost.
- In this case a supervisors waiting for this connection-ONLINE-telegram it will get stuck.

As the connection telegram is only sent when the AGV connects to or disconnects from the broker the impact on the network traffic should be hardly noticeable.

**Comment by collani-bosch** [comment]
I support this request. 
With bad WiFi conditions it's overall hard to determine the state of the communication with the vehicle(s). If a vehicle doesn't react (at once) on an order / instantAction in its state the handling of this issue inside the fleet management goes into the direction of a solution quit similar to the QoS 1, but on a higher (and awkwardly) abstraction level.

**Comment by TobiasScholz234** [comment]
We support this request, as we already noticed during the AGV MeshUp2021 problems with QoS0.

**Comment by KIT-IFL** [comment]
Changed in 9fd6704.
