### ISSUE TITLE
Simple Sectioning/Numbering Error

### ISSUE THREAD

**Issue by gauspohl** [VDA5050/VDA5050#244]
The table of contents has 6.14 and 6.15 looking fine, all good:
![image](https://github.com/VDA5050/VDA5050/assets/3812898/02066564-6ee2-4b1f-8efd-f1e5f32195bf)

However in the text itself, it jumps from 6.14 directly to 6.16
![image](https://github.com/VDA5050/VDA5050/assets/3812898/35e9600c-6f0e-4eb2-af34-8fcee3400f49)
![image](https://github.com/VDA5050/VDA5050/assets/3812898/f0f9f2b8-9b75-46b4-802f-df02fc360d73)

**Comment by AntonDueck** [comment]
in [dev/2.0.1](https://github.com/VDA5050/VDA5050/blob/dev/2.0.1/VDA5050_EN.md) it is all ready fixed.
