### ISSUE TITLE
initPosition incorrectly lists ".agvPosition.lastNodeId" field in section 6.8.2

### ISSUE THREAD

**Issue by erikjw** [VDA5050/VDA5050#245]
In the table of predefined actions in section 6.8.2, initPosition's "finished" column lists `agvPosition.lastNodeId` among the updated fields reported by the AGV.  

![image](https://github.com/VDA5050/VDA5050/assets/12835903/03e541a0-1a89-4caa-b742-d699ca8c8f99)

However, the `agvPosition` object does not include `lastNodeId` among its members.  Instead, `lastNodeId` is a member of the `state` message.   Therefore, the column in this table should reference `.lastNodeId` instead of `.agvPosition.lastNodeId` (as the table in section 6.8.1 correctly does in its linked state column).

**Comment by AntonDueck** [comment]
in (dev/2.0.1)[https://github.com/VDA5050/VDA5050/blob/dev/2.0.1/VDA5050_EN.md] it is already fixed
