### ISSUE TITLE
instantActions.schema has no required header fields

### ISSUE THREAD

**Issue by blumenthal** [VDA5050/VDA5050#247]
Dear VDA5050 development team,

I spotted a minor inconsistency in the JSON schema definition files.

Per documentation *Each JSON starts with a header.*  (see section 6.4 Protocol Header). However, the [`instantActions.schema`](https://github.com/VDA5050/VDA5050/blob/main/json_schemas/instantActions.schema) is not enforcing this. Other schema files use a `required` field for this.

I think what is missing is the following:   

```JSON
"required": [
    "headerId",
    "timestamp",
    "version",
    "manufacturer",
    "serialNumber",
    "actions"
]
```

**Comment by AntonDueck** [comment]
if you look at 
[dev/2.0.1](https://github.com/VDA5050/VDA5050/blob/5f8c1210b5c28e9465a5a120b80c93755ef99358/json_schemas/instantActions.schema#L5C11-L5C11)
it will be fixed in den next release.
