### ISSUE TITLE
Action parameters value - always string?

### ISSUE THREAD

**Issue by LukasSchwarz4202** [VDA5050/VDA5050#25]
In Vda5050 spec V1.1 chapter 7.2 a line says
```
Der Grund für die Verwendung des vorgeschlagenen Schemas “key”: “actualKey”, “value”: “actualValue”
besteht darin, die Implementierung durchgängig zu halten. Dies ist in mehreren Sitzungen gründlich und
kontrovers diskutiert worden.
``` 
in my opinion it means, that "value" has to be a string (“actualValue” is surrounded by **"**). 

The current discussions on the AGV-factsheet suggest for _valueDataType_
```
data type of Value, possible data types are 
BOOL, NUMBER, INTEGER, FLOAT, STRING, OBJECT, ARRAY 
```
Can this be interpreted in the way that _valueDataType_ describes the format of the _value_ string or should this be 'fixed' in one of the two documents?

**Comment by KIT-IFL** [comment]
As defined here: https://github.com/VDA5050/vd-m-a-5050/blob/5.0.0/order.schema#L429
the parameters can be of any data type. This should be alright, since they are action specific, so type mismatches should not pose a problem.
