### ISSUE TITLE
fieldViolation : safetyState 

### ISSUE THREAD

**Issue by HardyBenjamin** [VDA5050/VDA5050#260]
Hello,

The "fieldViolation" parameter is TRUE if the field is violated at the time the "STATE" message is sent?

The AGV does not send the information if a violation of the field has occurred? With the id of the edge on which the event occurred.

Thanks,

**Comment by collani-bosch** [comment]
Correct: a "field violation" isn't a trigger; maybe the vehicle sends a new state, but you cannot rely on. 
```
Events that trigger the transmission of the state message are: 
- Receiving an order 
- Receiving an order update 
- Changes in the load status 
- Errors or warnings 
- Driving over a node 
- Switching the operating mode 
- Change in the "driving" field 
- Change in the nodeStates, edgeStates or actionStates
```
