### ISSUE TITLE
How to Remove Released Nodes and Edges Without CancelOrder？

### ISSUE THREAD

**Issue by Benjamin-Miller1** [VDA5050/VDA5050#296]
How do I remove the released path on the AGV without canceling the order, because I want the AGV to continue to execute the order while the HMI keeps displaying information about the order.

**Comment by bekirbostanci** [comment]
You should keep the orderId same but increase orderUpdateId, in the new order create new path just important part is last node position of your robot. 
![image](https://github.com/VDA5050/VDA5050/assets/26343575/cb4f7786-c9c0-4ce4-baa4-9e868a20e218)

**Comment by cpaulsynaos** [comment]
(Un)Fortunately, it is not possible to change the released/base path of an order.
See chapter 6.6.2 for reasoning:
> Since MQTT is an asynchronous protocol and transmission via wireless networks is not reliable, it is important to note, that the "base" cannot be changed. The master control can therefore assume that the "base" is executed by the AGV.

The proposal of @bekirbostanci is not correct, as the important part for sending an order update is not the last node position of the robot, but the last node of the base of the former order update that was sent by master control.

The relevant path in the figure @bekirbostanci posted above is:
![grafik](https://github.com/VDA5050/VDA5050/assets/85339556/07bccf3b-c55d-46c8-8458-d01c1cfbf495)

**Comment by bekirbostanci** [comment]
@cpaulsynaos 
If the first node of the new order is the last released node of the old order and the master controller creates a virtual node at the location where the robot is currently located and a new order is created by adding the new path robot to this virtual node, will there be any problems in this case?
Because the old base last node will be defined as the first node of the new order. This may not be the right approach,
![image](https://github.com/VDA5050/VDA5050/assets/26343575/b5b19853-32fa-4ac2-8288-888325143fe4)

**Comment by Benjamin-Miller1** [comment]
@bekirbostanci @cpaulsynaos Let me describe the problem I ran into: Suppose the master control sent multiple released paths to an AGV#1. In the process of AGV#1 movement, a person manually drags another AGV#2 to the released path. I hope the master control can ask AGV#1 to stop and clear the unfinished path after stopping. Meanwhile, I hope AGV#1 can know that it only needs to clear the released path. Instead of cancelling the whole order, the HMI of AGV#1 can still display the information of the order, and also report the corresponding orderId, lastNodeId, orderUpdateId and other information of the order, because I still need AGV#1 to execute the previous order. Just truncated the released path. Once AGV#2 is set to automatic mode, the two AGVs can work together. CancelOrder causes the AGV to clear the order information, which can inconvenience the person using the AGV.
I noticed 6.6.3. 

> In the event of an unplanned change in the base nodes, the order must be canceled by usingthe instantAction cancelOrder. 

The protocol was too absolute, so I came to find a solution.

**Comment by cpaulsynaos** [comment]
@bekirbostanci 
That might be possible in regards of sending a valid order updates and correctly extending the path from the last base node.
However, in that case the robot is still expected to move to "3. Node 1#", then back to the virtual node you added, only then moving along the newly released path.

@Benjamin-Miller1 
Regarding order information to show on the HMI: I would not expect to have 1:1 relation between the VDA order and its triggering/superior transport order, as also stated in 6.6.1:
> An order message does not necessarily describe the full transport order. For traffic control and to accommodate resource constrained vehicles, the full transport order (which might consist of many nodes and edges) can be split up into many sub-orders

If you need information about those full transport orders to be shown on the HMI, you could perhaps use custom actions to transport this information.

**Comment by bekirbostanci** [comment]
@cpaulsynaos I have a another idea for this problem but maybe it is messy. He can create one custom action, it is skipNode and add the action on the new order first node.

**Comment by cpaulsynaos** [comment]
The Idea of the VDA 5050 is to allow interoperability by recommending at least some basic guarantees for both sides what to expect.

Of course everyone can add any custom behaviour on their side. But in case such customization affects core funcionality like movement or the guarantees on base and horizon - in your example: skipping nodes / bypassing any conditions - the other side would be required to adapt to such custom behaviour each time (e.g., for message validation, planning, traffic management).
Thus making the idea of a standard recommendation being less useful in my opinion.

**Comment by bekirbostanci** [comment]
Changing node position for that case doesn't need any custom action but yes, it might creates some side effects.
