### ISSUE TITLE
Length edge

### ISSUE THREAD

**Issue by HardyBenjamin** [VDA5050/VDA5050#300]
Hello,

The edge length is the distance between startNode center and endNode center ? Or between startNodeDeviationXY and endNodeDeviationXY ?

**Comment by collani-bosch** [comment]
Between the center of the nodes: The allowedDeviationXY is
a) optional (and the presence of an optional attribute shall not change the semantic of another attribute)
b) only an additional requirement which shall be meet, when a node is reported as passwd by the vehicle.
