### ISSUE TITLE
Confusing Type from Field "theta" in "boundingBoxReference" 

### ISSUE THREAD

**Issue by GSISeanHuang** [VDA5050/VDA5050#305]
Hi, 
I notice that the field "theta" in object `boundingBoxReference` of `factsheet.schema` is "integer"
```
                                "theta": {
                                    "type": "integer",
                                    "description": "Orientation of the loads bounding box. Important for tugger trains, etc."
                                }
```
However the corresponding parameter in `state.schema` is "number"
```
                            "theta": {
                                "type": "number",
                                "description":"Orientation of the loads bounding box. Important for tugger, trains, etc."
                            }
```
It should be consistent since they are same reference as follow.
I believe it should be type "number" in both case right?

**Comment by AntonDueck** [comment]
as the VDA 5050 Dokument says it is the same as in loads[] in the state and the document always right, the error in the fact sheet can be fixed. As the version 2.1 is about to release,  I do not know if we can change it before the release.
