### ISSUE TITLE
Whether the protocol requires a "edgeType" field to mark whether it is a line or a curve?

### ISSUE THREAD

**Issue by qiziqian** [VDA5050/VDA5050#308]
In our master control,if trajectory is null or an empty array, we think it is a straight line,on the other hand, it's a curve.But in our practice,we find manufactures don't do that,two very well-known manufacturers in China,one of them added an "type" field to "trajectory "with a value of "Straight" or "Curve",like this:
```
order->edges->edge
{"trajectory ":{
"type":"Straight"
......
}
}
```
The other one use "direction" field with value of "straight" or "curve":
```
order->edges->edge
{"direction":"striaght"}
```
  Both of the above is not in accordance with the protocol,so we perfer this:
```
order->edges->edge
{"edgeType":"STRAIGHT"}
```
  We think if the protocol has an "edgeType" field and some enumeration value,will be easier to understand and adapt

**Comment by collani-bosch** [comment]
The edge describes only a logical connection between two nodes and without the trajectory attribute no trajectory is defined by MC. Without the trajectory attributes MC can only make the assumption that the vehicle is able to move from the start node to the end node of an edge and (to simplify this) every time on the same trajectory. This assumption has to be ensured during the installation process of the system.
If you want to build a more sophisticated MC which takes the real driven trajectories into account for traffic control you have to "find a way" how to deposit the real trajectories (a vehicle is driving) inside your MC. A vehicle may or may not interpret an edge as a trajectory between two nodes, but the edge itself (without trajectory attribute) is only a logical connection.

**Comment by camil22** [comment]
I'm not sure what the meaning of edgeType has in your system. Do you want to distinguish lines at a turnout/junction on the edge or do you really want to know if the path to drive is curved or a straight line?
In the first case the direction property of the edge is appropriate. For the second case a vehicle can calculate whether the edge is curved or straight from the received trajectory. Since an edge could be composed of straight and curved segments such an edgeType is IMO difficult to standardize.

**Comment by qiziqian** [comment]
@camil22  I just describe the situation I encountered when debugging the vehicle. What I want is the second case you mentioned. Now it seems that the vehiclemanufacturer needs to find a more suitable adaptation method, thank you

**Comment by qiziqian** [comment]
@collani-bosch  I know you mean,you are right,I will close this issue
