### ISSUE TITLE
Discrepancy of maps in state message

### ISSUE THREAD

**Issue by christophprummer** [VDA5050/VDA5050#322]
While the state.schema in the repository contains a maps object, the pdf version of the VDA 5050 V2.1.0 does not. 

![image](https://github.com/user-attachments/assets/30e1c67a-5844-4961-bae6-17904a56693d)

**Comment by KIT-IFL** [comment]
Thank you for the important information, we have investigated it accordingly. Both the state.schema and the Markdown document on GitHub contain this entry. The PDF will be adapted accordingly, as this is the only way to achieve the behavior described in the maps chapter.
