### ISSUE TITLE
[Question]: Make 'informations[Info]' optional?

### ISSUE THREAD

**Issue by TobiasScholz234** [VDA5050/VDA5050#37]
To stick to the general specification of the VDA5050, not possible, required or existing data is _optional_ and therefore not mandatory to send, we suggest to make the JSON object 'informations[Info]' optional, instead of sending empty JSON objects.

This would also reduce the general primary data content of each telegram.

![3](https://user-images.githubusercontent.com/81621022/124468055-efa0ea80-dd98-11eb-8361-d61b048d7565.png)

**Comment by KIT-IFL** [comment]
Changed in 9219dce.
