### ISSUE TITLE
[BUG]: enumerations are camelCase and not UPPERCASE

### ISSUE THREAD

**Issue by LukasSchwarz4202** [VDA5050/VDA5050#4]
Chapter 6.1.3 (page 10) states that enumerations have be in upper case. Still the following enumerations are in lower case:
- _state->actionState->actionStatus_ (page 39)
- _state->error->errorLevel_ (page 40)
- _state->safetyState->eStop_ (page 40)

**Comment by ralienpp** [comment]
This also applies to action blocking types in section 6.12, they're capitalized, though in other parts of the spec camelCase is used for other elements of the protocol.

**Comment by KIT-IFL** [comment]
It was discussed during meetings that all values for enumerations shall be UPPERCASE. Whenever this is not the case, be it in the JSON Schemata or in the specification document, it is an error.

For future implementations, please always use uppercase enums as values.

As soon as we have a process how to treat these bugfixes in regard to the specification document, we will update the document and schemata.

**Comment by stephanlante** [comment]
Discussion within VDA and VDMA started

**Comment by KIT-IFL** [comment]
Fixed in https://github.com/VDA5050/VDA5050/commit/3d4590b828943f2247eed1b10c72b45062ec6204
