### ISSUE TITLE
Define a uniform way of declaring datatypes in the specification

### ISSUE THREAD

**Issue by daniel-kampen-synaos** [VDA5050/VDA5050#43]
In the specification we currently use different approaches to declare the datatype of specific fields. E.g. compare 6.7 `orderUpdateId: Integer` and 6.10.6 `orderUpdateId: Uint32`. This can cause confusions and might be even hindering in the communication between AGV and MC.

Currently this mainly applies to Integer vs uint32.

The work groups should decide which notation for the datatype should be used.

**Comment by KIT-IFL** [comment]
Fixed in 95dd509.
