### ISSUE TITLE
[Improvement]: 'instantActions' in topic 'instantActions'

### ISSUE THREAD

**Issue by LukasSchwarz4202** [VDA5050/VDA5050#6]
On the one hand, the actions-arrays are named _actions_ in the topic _order_ for both the node-actions as well as the _edge_-actions. On the other hand, the actions-array is named '_instantActions_' in the topic '_instantActions_'. => Rename for consistency reasons?

**Comment by KIT-IFL** [comment]
I think the node-actions and the edge-actions shoudl be renamed to camelCase: nodeActions and edgeActions.

**Comment by KIT-IFL** [comment]
Fixed in https://github.com/VDA5050/VDA5050/commit/335559844d6a496a3c80a269dbb58c070203ed70
