### ISSUE TITLE
sequenceId for actions?

### ISSUE THREAD

**Issue by MaximilianJohannesObpacher** [VDA5050/VDA5050#60]
Sometimes there are several actions that should be executed on one node. Is there a best practice of guaranteing the order of actions? Would it make sense to add an action sequenceId?

**Comment by AntonDueck** [comment]
You do no need it as it dis described in: 

**6.12 Action Blocking Types and sequence**

the order in array it the execution order.

**Comment by KIT-IFL** [comment]
https://github.com/VDA5050/VDA5050/blob/main/VDA5050_EN_V1.md#-612-action-blocking-types-and-sequence
Here's the link.
