### ISSUE TITLE
[Question] Lifetime of NONE-blocking Actions

### ISSUE THREAD

**Issue by jroeger23** [VDA5050/VDA5050#7]
Hello!

Consider the following Order:

![image1](https://user-images.githubusercontent.com/19974233/112166237-bd0b2180-8bef-11eb-872b-1e04ce6ebb70.png)

_Actions A1 and A2 are attached to N0, A3 is attached to E1_

VDA5050 states, that A3 has to finish (either failure or success) as soon as the AGV enters N2.

Does this also hold for A1 and A2, or may they run beyond
N2?

**Comment by KIT-IFL** [comment]
As far as I remember the discussions regarding the nodeActions, they are allowed to persist (like a mode change for say changing what a display says).

Then again I could be wrong. I hope that others will soon chime in.

**Comment by KIT-IFL** [comment]
https://github.com/VDA5050/VDA5050/blame/development/VDA5050_EN_V1.md#L743

It is mentioned here that actions on the nodes may run beyond node N2 in your picture. I hope this clarifies your question. If so, please close the issue.
