### ISSUE TITLE
JSON Schema uses invalid type "date-time"

### ISSUE THREAD

**Issue by jabbenseth** [VDA5050/VDA5050#77]
Looking at https://github.com/VDA5050/VDA5050/blob/5367d4555529415c07a58c10d4f6ceb903b0a56d/json_schemas/order.schema#L24
the type specification "date-time" is used. 
According to http://json-schema.org/draft/2019-09/json-schema-validation.html#rfc.section.6.1.1 only one of six basetypes is permitted and the specification according to the standard would have type `string` and make use of the `format` field:

```
        "timestamp": {
            "type": "string",
            "format": "date-time",
            "description": "Timestamp in ISO8601 format.",
            "examples": [
                "1991-03-11T11:40:03.12Z"
            ]
        },
```

The link to "order.schema" is only exemplary and the same thing can be seen in all jsonschemas.

**Comment by KIT-IFL** [comment]
Thank you!
Fixed in https://github.com/VDA5050/VDA5050/commit/c2b33cd40a8cac8414c4e44384f287ca71a3e371.
