### ISSUE TITLE
[Question] How to schedule instant Actions? (blocking types)

### ISSUE THREAD

**Issue by jroeger23** [VDA5050/VDA5050#8]
_NOTE: This question concerns only instant actions which correspond
to AGV actions (not special actions like cancelOrder)_

### Example scenario

Let's say the AGV is currently running a NONE-blocking action A1. Then a HARD-blocking instant action A2 was received.

I can think of the following behaviors:
- A1 is paused, the AGV stops, A2 is executed, the AGV resumes driving, A1 is resumed
- The AGV stops, A1 is finished, A2 is executed, the AGV resumes driving
- A1 is finished, The AGV stops, A2 is executed, the AGV resumes driving

Those difficulties also appear with other combinations of 
blocking types.

### Questions

Is there meant to be a standard way of scheduling actions
(e.g. by first come, first serve or some kind of blocking type priority)?

Are instant actions allowed to preempt running actions?

**Comment by KIT-IFL** [comment]
For your first question:
Actions should queue up according to their position in the list.
https://github.com/VDA5050/VDA5050/blob/main/VDA5050_EN_V1.md#-612-action-blocking-types-and-sequence

For your second question:
This is not well defined right now. Instant actions were added to the protocol to allow for an instantaneuous execution of the action.
Thus, I suggest that the instantAction preempts the other action.

I think the preempted running action should not resume. This could lead to unexpected behaviour on the operator side - e.g. you use the instantAction to reposition a LHD, but the previous action that was paused then positions it to somewhere else again.

**Comment by jroeger23** [comment]
Thanks, for now this seems reasonable to work with.
