### ISSUE TITLE
[Question] for node array in order content. Is it valid that  add two nodes with the same nodeId but different nodePositions.

### ISSUE THREAD

**Issue by wujianjin** [VDA5050/VDA5050#97]
for node array in order content. Is it valid that  add two nodes with the same nodeId but different nodePositions.
for example ：
"nodes": [
        { "nodeId":"1", "nodePosition":{"x“: 1000, "y": 1000 } },
        { "nodeId":"1", "nodePosition":{"x“: 1500, "y": 1000 } }
    ]

**Comment by AntonDueck** [comment]
it is possible as log the nodes have driffrent sequenceId. 

But then your edges get crazy because the startNodeId is identical to  endNodeId. 

then it get vehicle dependet what will happen. 

but if there are some nodes in between it is less problematik.

**Comment by wujianjin** [comment]
thank you for the reply so quickly.
if two node has same nodeId  and sequenceId is invalid, I can increment the second node's  sequceceId, its simple.

in our system, nodeId，startNodeId and endNodeId is not needed. AMR only care the base command position and the line style（straight line or cruve）,velocity ...

so for simple just I want is set the nodeId always be a constant ,for example  be 1, and let amr always update the base command to the second node.  amr need to ommit "the startNodeId is identical to endNodeId"

for example  in our system:
amr position (1000mm, 1000mm, 0) 
T1: send  (1500mm,  1000mm, 0) straight line
T2: send  (1555mm, 1000mm, 0) amr will update base command to (1555mm, 1000mm, 0)

follow VDA ptotocal
T1: orderId: 0,
{ "nodeId":"1", "nodePosition":{"x“: 1000mm, "y": 1000mm } },
{ "nodeId":"1", "nodePosition":{"x“: 1500mm, "y": 1000mm } }
need amr  ommit "the startNodeId is identical to endNodeId"

T2：orderId: 1,
{ "nodeId":"1", "nodePosition":{"x“: 1500mm, "y": 1000mm } },
{ "nodeId":"1", "nodePosition":{"x“: 1555mm, "y": 1000mm } }
also need amr  ommit "the startNodeId is identical to endNodeId"


also in VDA ptotocal 
if we have two point
{ "nodeId":"1", "nodePosition":{"x“: 0mm, "y": 1000mm } },
{ "nodeId":"2", "nodePosition":{"x“: 100000mm, "y": 1000mm } }

if amr posinion is (50000mm, 1000mm) i want amr  go to  (50020mm, 1000mm)，there is not a node which position is  (50000mm, 1000mm,) and also no nodeId whitch  (50020mm, 1000mm).  how VDA solve this case, use random nodeId ?

**Comment by wujianjin** [comment]
> it is possible as log the nodes have driffrent sequenceId.
> 
> But then your edges get crazy because the startNodeId is identical to endNodeId.
> 
> then it get vehicle dependet what will happen.
> 
> but if there are some nodes in between it is less problematik.





thank you for the reply so quickly.
if two node has same nodeId and sequenceId is invalid, I can increment the second node's sequceceId, its simple.

in our system, nodeId，startNodeId and endNodeId is not needed. AMR only care the base command position and the line style（straight line or cruve）,velocity ...

so for simple just I want is set the nodeId always be a constant ,for example be 1, and let amr always update the base command to the second node. amr need to ommit "the startNodeId is identical to endNodeId"

for example in our system:
amr position (1000mm, 1000mm, 0)
T1: send (1500mm, 1000mm, 0) straight line
T2: send (1555mm, 1000mm, 0) amr will update base command to (1555mm, 1000mm, 0)

follow VDA ptotocal
T1: orderId: 0,
{ "nodeId":"1", "nodePosition":{"x“: 1000mm, "y": 1000mm } },
{ "nodeId":"1", "nodePosition":{"x“: 1500mm, "y": 1000mm } }
need amr ommit "the startNodeId is identical to endNodeId"

T2：orderId: 1,
{ "nodeId":"1", "nodePosition":{"x“: 1500mm, "y": 1000mm } },
{ "nodeId":"1", "nodePosition":{"x“: 1555mm, "y": 1000mm } }
also need amr ommit "the startNodeId is identical to endNodeId"

also in VDA ptotocal
if we have two point
{ "nodeId":"1", "nodePosition":{"x“: 0mm, "y": 1000mm } },
{ "nodeId":"2", "nodePosition":{"x“: 100000mm, "y": 1000mm } }

if amr position is (50000mm, 1000mm) i want amr go to (50020mm, 1000mm)，there is not a node which position is (50000mm, 1000mm,) and also no nodeId whitch (50020mm, 1000mm). how VDA sugget to solve this case, use random nodeId ?
